import { useMutation } from '@tanstack/react-query';
import { api, ApiError } from '../api/client';

interface PortfolioSummaryResult {
  configured: boolean;
  summary: string | null;
  factsAsOf: string | null;
  error: string | null;
}

/** e.g. "2:34 PM" locally, or the date too if the facts are from an earlier day. */
function formatFactsAsOf(iso: string): string {
  const date = new Date(iso);
  const isToday = date.toDateString() === new Date().toDateString();
  return isToday
    ? date.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })
    : date.toLocaleString('en-US', {
        month: 'short',
        day: 'numeric',
        hour: 'numeric',
        minute: '2-digit',
      });
}

/**
 * Clearly separated from the app's own computed figures: this is an opinion
 * generated by a model reading a snapshot, not a measurement, so it gets its
 * own visual register (dashed border, an explicit "AI" badge, the exact
 * moment the underlying facts were read) rather than looking like another
 * stat tile.
 */
function ResultCard({ result }: { result: PortfolioSummaryResult }) {
  if (!result.configured) {
    return (
      <p className="text-xs text-muted">
        AI summaries aren't set up yet. Ask the developer to add an LLM API
        key.
      </p>
    );
  }

  if (result.error || !result.summary) {
    return (
      <p className="text-xs text-muted">
        {result.error ?? "Couldn't generate a summary just now. Try again in a bit."}
      </p>
    );
  }

  return (
    <div className="space-y-2 rounded-xl border border-dashed border-accent/40 bg-surface-1 p-3">
      <div className="flex items-center gap-2 text-[10px] uppercase tracking-wide text-accent">
        <span className="rounded bg-accent/15 px-1.5 py-0.5 font-medium">
          AI generated
        </span>
        {result.factsAsOf && (
          <span className="text-muted normal-case">
            from data as of {formatFactsAsOf(result.factsAsOf)}
          </span>
        )}
      </div>
      <p className="whitespace-pre-wrap text-sm leading-relaxed text-text">
        {result.summary}
      </p>
    </div>
  );
}

export function AiSummary() {
  const mutation = useMutation({
    mutationFn: () => api<PortfolioSummaryResult>('/ai/portfolio-summary', { method: 'POST' }),
  });

  return (
    <section className="space-y-2">
      <button
        type="button"
        onClick={() => mutation.mutate()}
        disabled={mutation.isPending}
        className="w-full rounded-lg border border-accent/40 bg-accent/10 px-4 py-2.5 text-sm font-medium text-accent active:bg-accent/20 disabled:opacity-60"
      >
        {mutation.isPending ? (
          <span className="inline-flex items-center justify-center gap-2">
            <span className="inline-block h-3.5 w-3.5 animate-spin rounded-full border-2 border-accent/30 border-t-accent" />
            Thinking…
          </span>
        ) : (
          'Give me an AI summary'
        )}
      </button>

      {mutation.isSuccess && <ResultCard result={mutation.data} />}

      {mutation.isError && (
        <p className="text-xs text-muted">
          {mutation.error instanceof ApiError
            ? "Couldn't reach the AI summary right now. Try again in a bit."
            : "Something went wrong generating the summary. Try again in a bit."}
        </p>
      )}
    </section>
  );
}
