import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, ApiError } from '../api/client';
import { streamNdjson } from '../api/streamNdjson';
import { formatTimestamp } from './format';
import { Markdown } from './Markdown';
import { EditModeToggle } from './ui/EditModeToggle';
import { CollapsibleCard } from './ui/CollapsibleCard';

/** Mirrors `LlmFailureKind` in `backend/src/llm/llm.client.ts`. */
type ErrorKind = 'busy' | 'quota_exceeded' | 'setup_problem' | 'unknown';

interface PortfolioSummaryResult {
  configured: boolean;
  summary: string | null;
  factsAsOf: string | null;
  error: string | null;
  /** Why `error` is set — `error` already carries the right copy for it, so today this is only here for future use (e.g. hiding "try again" for `setup_problem`). */
  errorKind: ErrorKind | null;
  /** The saved summary's id — null when nothing was persisted (unconfigured or failed). */
  id: string | null;
}

/** One line of `POST /ai/portfolio-summary/stream`'s newline-delimited JSON
 * — either a text delta, or the one final line carrying everything else
 * `PortfolioSummaryResult` has (see the backend's own `PortfolioSummaryStreamDone`). */
type SummaryStreamLine =
  | { delta: string }
  | (Omit<PortfolioSummaryResult, 'summary'> & { done: true });

const UNREACHABLE_ERROR = "Couldn't reach the AI summary right now. Try again in a bit.";
const GENERATION_ERROR = 'Something went wrong generating the summary. Try again in a bit.';

type GenerateState =
  | { status: 'idle' }
  | { status: 'streaming'; text: string }
  | { status: 'done'; result: PortfolioSummaryResult }
  | { status: 'error'; message: string };

interface AiSummaryListRow {
  id: string;
  createdAt: string;
  factsAsOf: string;
  preview: string;
}

interface AiSummaryDetail {
  id: string;
  summary: string;
  factsSnapshot: string;
  model: string;
  grounded: boolean;
  factsAsOf: string;
  createdAt: string;
}

const HISTORY_QUERY_KEY = ['ai-summaries'];

/**
 * Clearly separated from the app's own computed figures: this is an opinion
 * generated by a model reading a snapshot, not a measurement, so it gets its
 * own visual register (dashed border, an explicit "AI" badge, the exact
 * moment the underlying facts were read) rather than looking like another
 * stat tile.
 */
function ResultCard({ result }: { result: PortfolioSummaryResult }) {
  if (!result.configured) {
    return (
      <p className="text-xs text-muted">
        AI summaries aren't set up yet. Ask the developer to add an LLM API
        key.
      </p>
    );
  }

  if (result.error || !result.summary) {
    return (
      <p className="text-xs text-muted">
        {result.error ?? "Couldn't generate a summary just now. Try again in a bit."}
      </p>
    );
  }

  return (
    <CollapsibleSummary summary={result.summary} factsAsOf={result.factsAsOf} />
  );
}

/**
 * A generated summary runs to several hundred words, which on a phone buries
 * everything below it — the history list, and the button that makes the next
 * one. Collapsing keeps the result available without making the rest of the
 * screen unreachable.
 *
 * Open on arrival: it was just asked for, so hiding it would be perverse. The
 * header is the toggle, so there is no separate control to find.
 */
function CollapsibleSummary({
  summary,
  factsAsOf,
}: {
  summary: string;
  factsAsOf: string | null;
}) {
  return (
    <CollapsibleCard
      label="summary"
      header={
        <>
          <span className="rounded bg-accent/15 px-1.5 py-0.5 text-[10px] font-medium uppercase tracking-wide text-accent">
            AI generated
          </span>
          {factsAsOf && (
            <span className="text-[10px] text-muted">
              from data as of {formatTimestamp(factsAsOf)}
            </span>
          )}
        </>
      }
    >
      <Markdown text={summary} />
    </CollapsibleCard>
  );
}

/** The full record for one history row: the same badge/body treatment as a fresh result, plus its facts snapshot, collapsed by default — context, not the headline. */
function HistoryDetail({ id }: { id: string }) {
  const { data, isLoading, isError } = useQuery({
    queryKey: [...HISTORY_QUERY_KEY, id],
    queryFn: () => api<AiSummaryDetail>(`/ai/summaries/${id}`),
  });

  if (isLoading) {
    return <p className="px-3 pb-3 text-xs text-muted">Loading…</p>;
  }
  if (isError || !data) {
    return <p className="px-3 pb-3 text-xs text-muted">Couldn't load this summary.</p>;
  }

  return (
    <div className="space-y-2 border-t border-border px-3 pb-3 pt-2">
      <div className="flex flex-wrap items-center gap-2 text-[10px] uppercase tracking-wide text-accent">
        <span className="rounded bg-accent/15 px-1.5 py-0.5 font-medium">
          AI generated
        </span>
        <span className="text-muted normal-case">
          from data as of {formatTimestamp(data.factsAsOf)}
        </span>
      </div>
      <Markdown text={data.summary} />
      <details className="text-xs">
        <summary className="cursor-pointer select-none font-medium text-accent">
          Facts snapshot
        </summary>
        <pre className="mt-1.5 max-h-64 overflow-y-auto whitespace-pre-wrap break-words rounded-lg bg-surface-2 p-2 text-[11px] leading-relaxed text-muted">
          {data.factsSnapshot}
        </pre>
      </details>
    </div>
  );
}

interface HistoryRowProps {
  row: AiSummaryListRow;
  isOpen: boolean;
  onToggle: () => void;
  /** Delete is offered only in edit mode — see EditModeToggle. */
  editMode: boolean;
  pendingDelete: boolean;
  onRequestDelete: () => void;
  onCancelDelete: () => void;
  onConfirmDelete: () => void;
  isDeleting: boolean;
}

/**
 * One saved summary in the history list. Delete is two taps, never one — a
 * phone screen is exactly where a stray tap on a destructive action happens,
 * and this record can't be recovered once removed.
 */
function HistoryRow({
  row,
  isOpen,
  onToggle,
  editMode,
  pendingDelete,
  onRequestDelete,
  onCancelDelete,
  onConfirmDelete,
  isDeleting,
}: HistoryRowProps) {
  return (
    <li className="overflow-hidden rounded-lg border border-border bg-surface-1">
      <button
        type="button"
        onClick={onToggle}
        className="flex w-full items-start justify-between gap-2 px-3 py-2.5 text-left"
      >
        <span className="min-w-0 flex-1">
          <span className="block text-[10px] uppercase tracking-wide text-muted">
            {formatTimestamp(row.createdAt)}
          </span>
          <span className="mt-0.5 block truncate text-sm text-text">
            {row.preview}
          </span>
        </span>
        <span className="mt-1 shrink-0 text-[10px] text-muted">
          {isOpen ? '▲' : '▼'}
        </span>
      </button>

      {isOpen && <HistoryDetail id={row.id} />}

      {editMode && (
      <div className="border-t border-border px-3 py-2">
        {pendingDelete ? (
          <div className="flex items-center justify-between gap-2">
            <span className="text-xs text-muted">Delete this summary?</span>
            <span className="flex gap-2">
              <button
                type="button"
                onClick={onCancelDelete}
                className="rounded px-2 py-1 text-xs font-medium text-muted active:bg-surface-2"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={onConfirmDelete}
                disabled={isDeleting}
                className="rounded bg-down/10 px-2 py-1 text-xs font-medium text-down active:bg-down/20 disabled:opacity-60"
              >
                {isDeleting ? 'Deleting…' : 'Delete'}
              </button>
            </span>
          </div>
        ) : (
          <button
            type="button"
            onClick={onRequestDelete}
            className="text-xs font-medium text-down active:opacity-70"
          >
            Delete
          </button>
        )}
      </div>
      )}
    </li>
  );
}

export function AiSummary() {
  const queryClient = useQueryClient();
  const [showHistory, setShowHistory] = useState(false);
  const [openId, setOpenId] = useState<string | null>(null);
  const [pendingDeleteId, setPendingDeleteId] = useState<string | null>(null);
  const [editMode, setEditMode] = useState(false);

  const [generateState, setGenerateState] = useState<GenerateState>({ status: 'idle' });

  async function generate() {
    setGenerateState({ status: 'streaming', text: '' });
    let text = '';
    let receivedDone = false;

    try {
      await streamNdjson<SummaryStreamLine>('/ai/portfolio-summary/stream', (line) => {
        if ('done' in line) {
          receivedDone = true;
          const { done: _done, ...result } = line;
          setGenerateState({ status: 'done', result: { ...result, summary: text } });
          if (line.configured && !line.error) {
            // A fresh summary just got persisted — the history list, if
            // open, should reflect it without a manual reload.
            void queryClient.invalidateQueries({ queryKey: HISTORY_QUERY_KEY });
          }
        } else {
          text += line.delta;
          setGenerateState({ status: 'streaming', text });
        }
      });
    } catch (err) {
      setGenerateState({
        status: 'error',
        message: err instanceof ApiError ? UNREACHABLE_ERROR : GENERATION_ERROR,
      });
      return;
    }

    if (!receivedDone) {
      // The connection ended without ever sending the final line — the
      // model's own words, if any arrived, are incomplete and untrustworthy
      // to show as a finished answer.
      setGenerateState({ status: 'error', message: GENERATION_ERROR });
    }
  }

  const historyQuery = useQuery({
    queryKey: HISTORY_QUERY_KEY,
    queryFn: () => api<AiSummaryListRow[]>('/ai/summaries'),
    enabled: showHistory,
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => api<{ ok: boolean }>(`/ai/summaries/${id}`, { method: 'DELETE' }),
    onSuccess: (_data, id) => {
      void queryClient.invalidateQueries({ queryKey: HISTORY_QUERY_KEY });
      setPendingDeleteId(null);
      setOpenId((current) => (current === id ? null : current));
    },
  });

  return (
    <section className="space-y-2">
      <button
        type="button"
        onClick={() => void generate()}
        disabled={generateState.status === 'streaming'}
        className="w-full rounded-lg border border-accent/40 bg-accent/10 px-4 py-2.5 text-sm font-medium text-accent active:bg-accent/20 disabled:opacity-60"
      >
        {generateState.status === 'streaming' ? (
          <span className="inline-flex items-center justify-center gap-2">
            <span className="inline-block h-3.5 w-3.5 animate-spin rounded-full border-2 border-accent/30 border-t-accent" />
            Thinking…
          </span>
        ) : (
          'Analyse my portfolio'
        )}
      </button>

      {generateState.status === 'streaming' && generateState.text && (
        // Growing text, not yet the finished card — no badge or timestamp
        // until the final line confirms what actually happened.
        <div className="rounded-xl border border-dashed border-accent/40 bg-surface-1 p-3">
          <Markdown text={generateState.text} />
        </div>
      )}

      {generateState.status === 'done' && <ResultCard result={generateState.result} />}

      {generateState.status === 'error' && (
        <p className="text-xs text-muted">{generateState.message}</p>
      )}

      <div>
        <button
          type="button"
          onClick={() => setShowHistory((v) => !v)}
          className="text-xs font-medium text-muted underline decoration-dotted underline-offset-4"
        >
          {showHistory ? 'Hide history' : 'Show history'}
        </button>

        {showHistory && (
          <div className="mt-2">
            {historyQuery.isLoading && (
              <p className="text-xs text-muted">Loading…</p>
            )}
            {historyQuery.isError && (
              <p className="text-xs text-muted">Couldn't load history.</p>
            )}
            {historyQuery.data && historyQuery.data.length === 0 && (
              <p className="text-xs text-muted">No summaries saved yet.</p>
            )}
            {historyQuery.data && historyQuery.data.length > 0 && (
              <div className="mb-1.5 flex items-center justify-between gap-2">
                <span className="text-[10px] uppercase tracking-wide text-muted">
                  Saved summaries
                </span>
                <EditModeToggle
                  on={editMode}
                  onChange={(next) => {
                    setEditMode(next);
                    // Leaving edit mode abandons a half-started delete.
                    if (!next) setPendingDeleteId(null);
                  }}
                  noun="summaries"
                />
              </div>
            )}
            {historyQuery.data && historyQuery.data.length > 0 && (
              <ul className="space-y-1.5">
                {historyQuery.data.map((row) => (
                  <HistoryRow
                    key={row.id}
                    row={row}
                    editMode={editMode}
                    isOpen={openId === row.id}
                    onToggle={() =>
                      setOpenId((current) => (current === row.id ? null : row.id))
                    }
                    pendingDelete={pendingDeleteId === row.id}
                    onRequestDelete={() => setPendingDeleteId(row.id)}
                    onCancelDelete={() => setPendingDeleteId(null)}
                    onConfirmDelete={() => deleteMutation.mutate(row.id)}
                    isDeleting={
                      deleteMutation.isPending &&
                      deleteMutation.variables === row.id
                    }
                  />
                ))}
              </ul>
            )}
          </div>
        )}
      </div>
    </section>
  );
}
